### PR TITLE
Towards building on multiple platforms (Linux, MacOS, and W10)

### PR DESCRIPTION
**Pull request by dennisguse**
* Extended CMake configuration (compatibility to 2.8, gcc 4.8, and general cleanup).
* Updated LPC-10 code.
* Fixed test for undefined symbols.

### CODE REVIEW

**Comment by dennisguse** [comment]
I partly integrated the changes for OSX (except the OpenSSL issue as it cannot be resolved in a satisfying way).
This patch should be ready for merging it into the master branch.

Tested on Ubuntu 16.10

@chohner Could you verify it still works on MACOS
It might be an issue that I changed find_package to find_library for OpenSSL.
I know that find_library ignores OPENSSL_ROOT_DIR.
If it doesn't work for you, we would need to go for find_library.
So, does it work for you? (thumbs pressed)

@michalsoloducha 
It would be really cool if you could check the Windows 10 Ubuntu Bash install guide.
And then: happy using ;)

**Comment by chohner** [comment]
Doesn't work unfortunately. `find_library(ssl)` will always go through with the unsecure Apple header but then simply fail to link later.

But you can avoid the hard-coded path by passing `-DOPENSSL_ROOT_DIR="/usr/local/opt/openssl"`. Would something like this work on unix?

```
find_package(OpenSSL)
if(NOT OpenSSL_FOUND)
  message(WARNING "OPENSSL NOT FOUND")
else()
  include_directories(${OPENSSL_INCLUDE_DIR})
endif()
```

I actually don't know why cmake is not including `OPENSSL_INCLUDE_DIR` automatically but this works on my end when passing the right `OPENSSL_ROOT_DIR`.

**Comment by dennisguse** [comment]
Ready for testing.
The last commit (Removed SSL linker...) removes the check for OpenSSL (find_library).
Works on Ubuntu, but I am not sure about MACOS.
 @chohner Could you test this?

Best!

**Comment by chohner** [comment]
The approach works. A couple of thoughts:
- Why removing the OPENSSL_FOUND check? Not having OpenSSL throws an unavoidable error for the optional websocket packages on all OS.
- Whats the reasoning for putting a few lines of conditionals into a new file?  It's still part of the make process and nicer to read when all in one place.
- I still think its nice to have find_package search the default brew path by default.

I would therefore revert https://github.com/TheTelephone/TheTelephone/pull/10/commits/15b4e6aac369d4764d4148c011097b01a08d1cea and do the following:

```
#OS dependent workarounds
if(${CMAKE_SYSTEM_NAME} STREQUAL "Darwin")
    ##Since 10.11, OSX ships with an old version of OpenSSL, without headers
    ##(see https://langui.sh/2015/07/24/osx-clang-include-lib-search-paths/).
    ##We assume "/usr/local/opt/openssl" as it is the default path after installing OpenSSL via Homebrew.
    ##You may pass your own using -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl
    find_path(OPENSSL_INCLUDE_DIR
      NAMES openssl/ssl.h
      PATHS "/usr/local/opt/openssl/include"
    )
endif()
```

```
find_package(OpenSSL)
if(OpenSSL_FOUND)
  include_directories(${OPENSSL_INCLUDE_DIR})
else()
  message(WARNING "OpenSSL header file could not be found. If OpenSSL is installed, please provide the path, e.g.,\n  cmake -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl .")
endif()
```

**Pull request merged**
